### ISSUE TITLE
Recent stays empty

### ISSUE THREAD

**Issue by VerstreuteSeele** [Joshua-Noakes1/Pibot#3]
Hey. when I try to execute the "recent" command it doesnt tell me the last blocked domain. it just shows this:

Recently Blocked Domain: '**'
Pihole ip: 192.168.1.7 •22/4/2021, 07:41:21

**Comment by VerstreuteSeele** [comment]
hello? anyone here?

**Comment by Joshua-Noakes1** [comment]
Hi, sorry for the delay
I've recently been away from maintaining this project but I'll happily look into it

**Comment by Joshua-Noakes1** [comment]
I've recently had quite a few people contact me with issues that they've been having with pibot, I believe that some API endpoints have changed between Pi-hole V4 and V5. There isn't very much API documentation from the Pi-hole devs so I'll have to look into what's changed and to see how it can be fixed. If you want you can put a list of issues you've found here and I'll see if I can fix them 😄

**Comment by Joshua-Noakes1** [comment]
I'll be closing this issue now
